name: Docker publish 🐳
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          labels: "sergioisidoro/hl7-pong"
          tag_with_ref: true
